pid /tmp/nginx.pid;
worker_processes auto;
error_log /dev/stderr warn;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  log_format concise escape=json '{"remote_addr":"$remote_addr","method":"$request_method","uri":"$uri","status":$status,"bytes":$body_bytes_sent,"user_agent":"$http_user_agent"}';
  access_log /dev/stdout concise;
  sendfile on;
  tcp_nopush on;
  keepalive_timeout 20s;
  keepalive_requests 500;
  client_header_timeout 15s;
  client_body_temp_path /tmp/client_temp;
  proxy_temp_path /tmp/proxy_temp;
  fastcgi_temp_path /tmp/fastcgi_temp;
  uwsgi_temp_path /tmp/uwsgi_temp;
  scgi_temp_path /tmp/scgi_temp;
  include /etc/nginx/conf.d/*.conf;
}
