import {Link} from 'react-router-dom'
import {Cell,Pie,PieChart,ResponsiveContainer,Tooltip} from 'recharts'
import type {Overview} from '../types'
import {SEVERITIES,SEVERITY_COLORS} from '../severity'

export default function DashboardCharts({overview}:{overview?:Overview}){
  const data=SEVERITIES.map(name=>({name,value:overview?.severity[name]||0})).filter(item=>item.value>0)
  const total=data.reduce((sum,item)=>sum+item.value,0)
  const maxImage=Math.max(1,...(overview?.most_vulnerable||[]).map(item=>item.total))
  const maxPackage=Math.max(1,...(overview?.risk_packages||[]).map(item=>item.total))
  return <div className="grid gap-5 lg:grid-cols-2 2xl:grid-cols-[1.15fr_1fr_1fr]">
    <section className="card overflow-hidden p-5 lg:col-span-2 2xl:col-span-1"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Risk composition</p><h2 className="mt-1 font-semibold">Severity distribution</h2></div>{data.length?<><div className="relative mx-auto h-64 max-w-md"><ResponsiveContainer><PieChart><defs>{data.map(item=><linearGradient key={item.name} id={`severity-${item.name}`} x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor={SEVERITY_COLORS[item.name]}/><stop offset="100%" stopColor={lighten(SEVERITY_COLORS[item.name])}/></linearGradient>)}</defs><Pie data={data} dataKey="value" nameKey="name" innerRadius={70} outerRadius={103} paddingAngle={3} cornerRadius={6} stroke="transparent">{data.map(item=><Cell key={item.name} fill={`url(#severity-${item.name})`}/>)}</Pie><Tooltip content={<SeverityTooltip total={total}/>}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-3xl font-bold">{total.toLocaleString()}</span><span className="text-xs font-medium uppercase tracking-wider text-slate-500">findings</span></div></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-5 2xl:grid-cols-2">{SEVERITIES.map(name=>{const value=overview?.severity[name]||0,percent=total?value/total*100:0;return <div key={name} className="rounded-lg border bg-slate-50 p-2.5"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{background:SEVERITY_COLORS[name]}}/><span className="text-[11px] font-bold">{name}</span></div><div className="mt-1 flex items-baseline justify-between"><b>{value.toLocaleString()}</b><span className="text-[10px] text-slate-500">{percent.toFixed(1)}%</span></div></div>})}</div></>:<Empty/>}</section>
    <RankedList title="Most vulnerable images" eyebrow="Image exposure" items={(overview?.most_vulnerable||[]).map(item=>({id:item.image_id,label:item.name,value:item.total}))} max={maxImage} links/>
    <RankedList title="Highest-risk packages" eyebrow="Package concentration" items={(overview?.risk_packages||[]).map((item,index)=>({id:index,label:item.name,value:item.total,detail:`${item.critical} critical`}))} max={maxPackage}/>
  </div>
}

function RankedList({title,eyebrow,items,max,links=false}:{title:string;eyebrow:string;items:{id:number;label:string;value:number;detail?:string}[];max:number;links?:boolean}){return <section className="card p-5"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">{eyebrow}</p><h2 className="mb-5 mt-1 font-semibold">{title}</h2><div className="space-y-4">{items.length?items.slice(0,7).map((item,index)=><div key={item.id}><div className="mb-1.5 flex items-center justify-between gap-3 text-sm"><div className="min-w-0 truncate"><span className="mr-2 text-xs font-bold text-slate-400">{String(index+1).padStart(2,'0')}</span>{links?<Link to={`/images/${item.id}`} className="font-medium hover:text-blue-700 hover:underline">{item.label}</Link>:<span className="font-medium">{item.label}</span>}</div><div className="shrink-0 text-right"><b>{item.value}</b>{item.detail&&<span className="ml-2 text-[10px] text-rose-700">{item.detail}</span>}</div></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{width:`${Math.max(4,item.value/max*100)}%`}}/></div></div>):<Empty/>}</div></section>}
function SeverityTooltip({active,payload,total}:{active?:boolean;payload?:Array<{name:string;value:number}>;total:number}){if(!active||!payload?.length)return null;const item=payload[0];return <div className="rounded-xl border bg-white p-3 shadow-xl"><div className="text-xs font-bold" style={{color:SEVERITY_COLORS[item.name]}}>{item.name}</div><div className="mt-1 text-lg font-bold">{item.value.toLocaleString()}</div><div className="text-xs text-slate-500">{total?(item.value/total*100).toFixed(1):0}% of findings</div></div>}
function Empty(){return <div className="flex h-full min-h-24 items-center justify-center text-sm text-slate-400">No saved scan data yet</div>}
function lighten(hex:string){const value=parseInt(hex.slice(1),16),r=Math.min(255,(value>>16)+45),g=Math.min(255,((value>>8)&255)+45),b=Math.min(255,(value&255)+45);return `#${((1<<24)+(r<<16)+(g<<8)+b).toString(16).slice(1)}`}
