import {useMemo,useState} from 'react'
import {NavLink} from 'react-router-dom'
import {BookOpenCheck,Check,ChevronDown,Clipboard,CodeXml,KeyRound,LoaderCircle,Play,Search,ShieldCheck,Terminal} from 'lucide-react'
import {useQuery} from '@tanstack/react-query'
import {api} from '../api'
import {errorMessage} from '../errors'

type JsonSchema={type?:string;format?:string;description?:string;example?:unknown;default?:unknown;enum?:unknown[];properties?:Record<string,JsonSchema>;required?:string[];items?:JsonSchema;$ref?:string;oneOf?:JsonSchema[];anyOf?:JsonSchema[];allOf?:JsonSchema[];nullable?:boolean}
type Parameter={name:string;in:string;required?:boolean;description?:string;schema?:JsonSchema;example?:unknown}
type Media={schema?:JsonSchema;example?:unknown;examples?:Record<string,{value?:unknown}>}
type ApiResponse={description?:string;content?:Record<string,Media>}
type Operation={summary?:string;description?:string;operationId?:string;tags?:string[];parameters?:Parameter[];requestBody?:{required?:boolean;content?:Record<string,Media>};responses?:Record<string,ApiResponse>;security?:Record<string,string[]>[];'x-layerscope-authentication'?:string;'x-layerscope-roles'?:string[]}
type OpenApiDocument={info:{title:string;version:string;description?:string};paths:Record<string,Record<string,Operation|Parameter[]>>;components?:{schemas?:Record<string,JsonSchema>}}
type Endpoint={path:string;method:string;operation:Operation}

const methods=new Set(['get','post','put','patch','delete','head','options'])
const methodStyle:Record<string,string>={get:'bg-blue-100 text-blue-800',post:'bg-emerald-100 text-emerald-800',put:'bg-amber-100 text-amber-800',patch:'bg-violet-100 text-violet-800',delete:'bg-rose-100 text-rose-800',head:'bg-cyan-100 text-cyan-800',options:'bg-slate-100 text-slate-700'}
const roleOrder=['viewer','operator','admin']

export default function ApiDocsPage(){
  const schema=useQuery({queryKey:['api-openapi'],queryFn:()=>api.get<OpenApiDocument>('/api/openapi.json'),staleTime:300_000})
  const [search,setSearch]=useState(''),[tag,setTag]=useState('all'),[role,setRole]=useState('all')
  const endpoints=useMemo(()=>schema.data?Object.entries(schema.data.paths).flatMap(([path,item])=>Object.entries(item).filter(([method])=>methods.has(method)).map(([method,operation])=>({path,method,operation:operation as Operation}))).sort((a,b)=>a.path.localeCompare(b.path)||a.method.localeCompare(b.method)):[],[schema.data])
  const tags=useMemo(()=>Array.from(new Set(endpoints.flatMap(endpoint=>endpoint.operation.tags||['Dashboard']))).sort(),[endpoints])
  const filtered=endpoints.filter(endpoint=>{
    const operation=endpoint.operation,haystack=`${endpoint.method} ${endpoint.path} ${operation.summary||''} ${operation.description||''} ${(operation.tags||[]).join(' ')}`.toLowerCase()
    const roles=operation['x-layerscope-roles']||[]
    return (!search.trim()||haystack.includes(search.trim().toLowerCase()))&&(tag==='all'||operation.tags?.includes(tag))&&(role==='all'||roles.includes(role)||(role==='public'&&operation['x-layerscope-authentication']==='public'))
  })
  if(schema.isLoading)return <div className="card p-10 text-center text-slate-500"><LoaderCircle className="mx-auto mb-3 animate-spin"/>Loading authenticated API schema...</div>
  if(schema.error||!schema.data)return <div className="card border-rose-200 p-8 text-center text-rose-700"><CodeXml className="mx-auto mb-3"/><h1 className="text-xl font-bold">API documentation unavailable</h1><p className="mt-2 text-sm">{errorMessage(schema.error,'The authenticated OpenAPI schema could not be loaded.')}</p></div>
  return <div className="mx-auto max-w-7xl space-y-6">
    <header><p className="text-sm font-medium text-blue-600">Authenticated developer reference</p><h1 className="flex items-center gap-3 text-3xl font-bold"><BookOpenCheck size={30}/>LayerScope API Docs</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-500">{schema.data.info.description}</p></header>
    <section className="grid gap-4 lg:grid-cols-3">
      <InfoCard icon={<ShieldCheck/>} title="Two authentication modes"><p>Browser requests use the HttpOnly session cookie and CSRF for mutations. Programs use <code>Authorization: Bearer lsp_…</code>. Never send both.</p></InfoCard>
      <InfoCard icon={<KeyRound/>} title="Personal API tokens"><p>Create, copy once, expire, and revoke tokens on the <NavLink className="font-semibold text-blue-700 hover:underline" to="/api-tokens">API tokens</NavLink> page. Every call inherits the owner's current role.</p></InfoCard>
      <InfoCard icon={<Terminal/>} title="Machine-readable schema"><p>Authenticated clients can read <code>/api/openapi.json</code>. Public <code>/docs</code> and <code>/redoc</code> routes remain disabled.</p></InfoCard>
    </section>
    <section className="card p-5"><div className="grid gap-3 lg:grid-cols-[1fr_220px_220px_auto]"><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-10" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search method, route, summary, or tag" aria-label="Search API documentation"/></label><select className="input" value={tag} onChange={event=>setTag(event.target.value)} aria-label="Filter by API category"><option value="all">All categories</option>{tags.map(value=><option key={value}>{value}</option>)}</select><select className="input" value={role} onChange={event=>setRole(event.target.value)} aria-label="Filter by required role"><option value="all">All access levels</option><option value="public">Public</option>{roleOrder.map(value=><option key={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select><div className="rounded-xl border bg-slate-50 px-4 py-2 text-center"><p className="text-lg font-bold">{filtered.length}</p><p className="text-xs text-slate-500">of {endpoints.length} operations</p></div></div></section>
    <section className="space-y-3">{filtered.map(endpoint=><EndpointCard key={`${endpoint.method}-${endpoint.path}`} endpoint={endpoint} document={schema.data}/>)}</section>
    {filtered.length===0&&<div className="card p-10 text-center text-slate-500">No API operations match these filters.</div>}
  </div>
}

function InfoCard({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <article className="card p-5"><span className="mb-3 inline-flex rounded-xl bg-blue-50 p-3 text-blue-700">{icon}</span><h2 className="font-semibold">{title}</h2><div className="mt-2 text-sm leading-6 text-slate-600">{children}</div></article>}

function EndpointCard({endpoint,document}:{endpoint:Endpoint;document:OpenApiDocument}){
  const {path,method,operation}=endpoint,roles=operation['x-layerscope-roles']||[],auth=operation['x-layerscope-authentication']||'session-or-bearer'
  const body=firstContent(operation.requestBody?.content),bodyExample=body?sampleFromMedia(body[1],document):undefined
  const url=`http://localhost:8080${examplePath(path,operation.parameters||[])}`
  const mutating=!['get','head','options'].includes(method)
  const curlAuth=auth==='public'?[]:auth==='browser-session-only'?[`  -b cookies.txt`,...(mutating?[`  -H "X-CSRF-Token: $LAYERSCOPE_CSRF"`]:[])]:[`  -H "Authorization: Bearer $LAYERSCOPE_TOKEN"`]
  const multipart=body?.[0]==='multipart/form-data'
  const curlBody=!body?[]:multipart?curlFormLines(body[1].schema,document):[`  -H "Content-Type: ${body[0]}"`,`  --data '${JSON.stringify(bodyExample)}'`]
  const curl=[`curl -X ${method.toUpperCase()} "${url}"`,...curlAuth,...curlBody].join(' \\\n')
  const psBody=!body?'':multipart?` -Form ${powerShellForm(body[1].schema,document)}`:` -ContentType '${body[0]}' -Body '${JSON.stringify(bodyExample).split("'").join("''")}'`
  const psAuth=auth==='public'?'':auth==='browser-session-only'?` -WebSession $session${mutating?' -Headers @{ "X-CSRF-Token" = $csrf }':''}`:' -Headers @{ Authorization = "Bearer $token" }'
  const powershell=`Invoke-RestMethod -Method ${method.toUpperCase()} -Uri '${url}'${psAuth}${psBody}`
  return <details className="card group overflow-hidden"><summary className="flex cursor-pointer list-none items-start gap-3 p-4 sm:items-center"><MethodBadge method={method}/><code className="min-w-0 flex-1 break-all pt-1 text-sm font-semibold text-slate-900 sm:pt-0">{path}</code><span className="hidden text-sm text-slate-500 lg:block">{operation.summary||'API operation'}</span><AccessBadge auth={auth} roles={roles}/><ChevronDown className="mt-1 shrink-0 text-slate-400 transition-transform group-open:rotate-180" size={18}/></summary><div className="space-y-6 border-t p-5">
    <div><h2 className="text-lg font-semibold">{operation.summary||humanize(operation.operationId||`${method} ${path}`)}</h2>{operation.description&&<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{operation.description}</p>}<div className="mt-3 flex flex-wrap gap-2">{(operation.tags||[]).map(value=><span key={value} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{value}</span>)}<AccessBadge auth={auth} roles={roles}/></div></div>
    <ParameterTable parameters={operation.parameters||[]}/>
    {body&&<section><h3 className="mb-2 font-semibold">Request body <span className="text-xs font-normal text-slate-500">{operation.requestBody?.required?'required':'optional'} · {body[0]}</span></h3><SchemaBlock value={{example:bodyExample,schema:body[1].schema}}/></section>}
    <ResponseDocs responses={operation.responses||{}}/>
    <section><h3 className="mb-3 flex items-center gap-2 font-semibold"><Clipboard size={17}/>Request examples</h3><div className="grid gap-3 xl:grid-cols-2"><CodeExample label="curl" value={curl}/><CodeExample label="PowerShell" value={powershell}/></div></section>
    <LiveGet endpoint={endpoint}/>
  </div></details>
}

function MethodBadge({method}:{method:string}){return <span className={`w-16 shrink-0 rounded-lg px-2 py-1 text-center text-xs font-black uppercase ${methodStyle[method]||'bg-slate-100 text-slate-700'}`}>{method}</span>}
function AccessBadge({auth,roles}:{auth:string;roles:string[]}){const publicAccess=auth==='public',label=publicAccess?'Public':auth==='browser-session-only'?'Session only':roles.length===3?'Authenticated':roles.join(' / ');return <span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${publicAccess?'bg-slate-100 text-slate-600':auth==='browser-session-only'?'bg-violet-50 text-violet-700':'bg-blue-50 text-blue-700'}`}>{label}</span>}

function ParameterTable({parameters}:{parameters:Parameter[]}){if(!parameters.length)return null;return <section><h3 className="mb-2 font-semibold">Parameters</h3><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Name</th><th className="p-3">Location</th><th className="p-3">Type</th><th className="p-3">Requirement</th><th className="p-3">Description</th></tr></thead><tbody>{parameters.map(parameter=><tr className="border-t" key={`${parameter.in}-${parameter.name}`}><td className="p-3 font-mono font-semibold">{parameter.name}</td><td className="p-3">{parameter.in}</td><td className="p-3 font-mono text-xs">{schemaType(parameter.schema)}</td><td className="p-3">{parameter.required?'Required':'Optional'}</td><td className="p-3 text-slate-500">{parameter.description||'—'}</td></tr>)}</tbody></table></div></section>}

function ResponseDocs({responses}:{responses:Record<string,ApiResponse>}){return <section><h3 className="mb-2 font-semibold">Responses</h3><div className="space-y-2">{Object.entries(responses).map(([status,response])=>{const content=firstContent(response.content);return <details className="rounded-xl border bg-slate-50" key={status}><summary className="flex cursor-pointer list-none items-center gap-3 p-3"><span className={`rounded-md px-2 py-1 font-mono text-xs font-bold ${status.startsWith('2')?'bg-emerald-100 text-emerald-800':status.startsWith('4')?'bg-amber-100 text-amber-800':'bg-slate-200 text-slate-700'}`}>{status}</span><span className="text-sm">{response.description||'Response'}</span>{content&&<span className="ml-auto text-xs text-slate-500">{content[0]}</span>}</summary>{content?.[1].schema&&<div className="border-t p-3"><SchemaBlock value={content[1].schema}/></div>}</details>})}</div></section>}

function CodeExample({label,value}:{label:string;value:string}){const [copied,setCopied]=useState(false);async function copy(){await navigator.clipboard.writeText(value);setCopied(true);window.setTimeout(()=>setCopied(false),1500)}return <div className="overflow-hidden rounded-xl border bg-slate-950 text-slate-100"><div className="flex items-center justify-between border-b border-slate-800 px-3 py-2 text-xs text-slate-400"><span>{label}</span><button className="flex items-center gap-1 hover:text-white" onClick={copy}>{copied?<Check size={14}/>:<Clipboard size={14}/>} {copied?'Copied':'Copy'}</button></div><pre className="overflow-x-auto p-3 text-xs leading-5"><code>{value}</code></pre></div>}

function LiveGet({endpoint}:{endpoint:Endpoint}){
  const parameters=endpoint.operation.parameters||[],pathParameters=parameters.filter(item=>item.in==='path'),queryParameters=parameters.filter(item=>item.in==='query')
  const [values,setValues]=useState<Record<string,string>>({}),[result,setResult]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const excluded=/\/(events|archive|raw|exports)(\/|$)|\/backups\/download\//.test(endpoint.path),canRun=endpoint.method==='get'&&!excluded
  if(!canRun)return <section className="rounded-xl border border-amber-200 bg-amber-50 p-4"><h3 className="font-semibold text-amber-900">Live execution is protected</h3><p className="mt-1 text-sm leading-6 text-amber-800">Use the generated API-client example for mutations, streams, evidence downloads, and single-use tickets. This prevents the documentation explorer from bypassing application confirmations or consuming a download unintentionally.</p></section>
  async function run(){let path=endpoint.path;for(const parameter of pathParameters){const value=values[parameter.name]?.trim();if(!value){setError(`Enter the required path parameter: ${parameter.name}`);return}path=path.replace(`{${parameter.name}}`,encodeURIComponent(value))}const query=new URLSearchParams();for(const parameter of queryParameters){const value=values[parameter.name]?.trim();if(!value)continue;if(parameter.schema?.type==='array')value.split(',').map(item=>item.trim()).filter(Boolean).forEach(item=>query.append(parameter.name,item));else query.set(parameter.name,value)}setBusy(true);setError('');setResult('');try{const response=await api.get<unknown>(`${path}${query.size?`?${query}`:''}`);const rendered=JSON.stringify(response,null,2);setResult(rendered.length>50_000?`${rendered.slice(0,50_000)}\n… response preview truncated`:rendered)}catch(value){setError(errorMessage(value,'Request failed'))}finally{setBusy(false)}}
  return <section className="rounded-xl border border-blue-200 bg-blue-50/40 p-4"><h3 className="flex items-center gap-2 font-semibold"><Play size={17}/>Live JSON request</h3><p className="mt-1 text-sm text-slate-600">Uses your current browser session. No API token is entered or stored here.</p>{parameters.length>0&&<div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[...pathParameters,...queryParameters].map(parameter=><label key={`${parameter.in}-${parameter.name}`}><span className="text-xs font-semibold text-slate-600">{parameter.name} · {parameter.in}{parameter.required?' · required':''}</span><input className="input mt-1" value={values[parameter.name]||''} onChange={event=>setValues(current=>({...current,[parameter.name]:event.target.value}))} placeholder={parameter.schema?.type==='array'?'Comma-separated values':schemaType(parameter.schema)}/></label>)}</div>}<button className="btn-primary mt-4" disabled={busy} onClick={run}>{busy?<LoaderCircle className="animate-spin" size={16}/>:<Play size={16}/>}Send GET</button>{error&&<p className="mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{result&&<pre className="mt-3 max-h-96 overflow-auto rounded-xl bg-slate-950 p-4 text-xs leading-5 text-slate-100"><code>{result}</code></pre>}</section>
}

function SchemaBlock({value}:{value:unknown}){return <pre className="max-h-96 overflow-auto rounded-xl bg-slate-950 p-4 text-xs leading-5 text-slate-100"><code>{JSON.stringify(value,null,2)}</code></pre>}
function firstContent(content?:Record<string,Media>):[string,Media]|undefined{const entry=Object.entries(content||{})[0];return entry as [string,Media]|undefined}
function schemaType(schema?:JsonSchema):string{if(!schema)return 'any';if(schema.$ref){const parts=schema.$ref.split('/');return parts[parts.length-1]||'object'}if(schema.type==='array')return `array<${schemaType(schema.items)}>`;return [schema.type||'object',schema.format].filter(Boolean).join(' · ')}
function humanize(value:string){return value.split('_').join(' ').replace(/\b\w/g,(letter:string)=>letter.toUpperCase())}
function examplePath(path:string,parameters:Parameter[]){let result=path;for(const parameter of parameters.filter(item=>item.in==='path'))result=result.replace(`{${parameter.name}}`,parameter.example===undefined?`<${parameter.name}>`:String(parameter.example));const query=parameters.filter(item=>item.in==='query'&&item.required).map(item=>`${encodeURIComponent(item.name)}=<${item.name}>`);return `${result}${query.length?`?${query.join('&')}`:''}`}
function sampleFromMedia(media:Media,document:OpenApiDocument){if(media.example!==undefined)return media.example;const named=Object.values(media.examples||{})[0]?.value;if(named!==undefined)return named;return sampleSchema(media.schema,document,0)}
function resolvedSchema(schema:JsonSchema|undefined,document:OpenApiDocument){if(!schema?.$ref)return schema;const parts=schema.$ref.split('/'),name=parts[parts.length-1]||'';return document.components?.schemas?.[name]||schema}
function formFields(schema:JsonSchema|undefined,document:OpenApiDocument){return Object.entries(resolvedSchema(schema,document)?.properties||{})}
function isFileField(schema:JsonSchema){return schema.format==='binary'||(schema.type==='array'&&schema.items?.format==='binary')}
function exampleFile(name:string){return name==='file'?'C:/path/to/backup.tdbackup':'C:/path/to/example-image.tar'}
function curlFormLines(schema:JsonSchema|undefined,document:OpenApiDocument){return formFields(schema,document).map(([name,value])=>`  -F "${name}=${isFileField(value)?`@${exampleFile(name)}`:`<${name}>`}"`)}
function powerShellForm(schema:JsonSchema|undefined,document:OpenApiDocument){const fields=formFields(schema,document).map(([name,value])=>`${name} = ${isFileField(value)?`Get-Item '${exampleFile(name)}'`:`'<${name}>'`}`);return `@{ ${fields.join('; ')} }`}
function sampleSchema(schema:JsonSchema|undefined,document:OpenApiDocument,depth:number):unknown{if(!schema||depth>4)return {};if(schema.example!==undefined)return schema.example;if(schema.default!==undefined)return schema.default;if(schema.enum?.length)return schema.enum[0];if(schema.$ref){const parts=schema.$ref.split('/'),name=parts[parts.length-1]||'';return sampleSchema(document.components?.schemas?.[name],document,depth+1)}if(schema.oneOf?.length)return sampleSchema(schema.oneOf[0],document,depth+1);if(schema.anyOf?.length)return sampleSchema(schema.anyOf[0],document,depth+1);if(schema.allOf?.length)return Object.assign({},...schema.allOf.map(item=>sampleSchema(item,document,depth+1)));if(schema.type==='array')return [sampleSchema(schema.items,document,depth+1)];if(schema.type==='object'||schema.properties)return Object.fromEntries(Object.entries(schema.properties||{}).map(([key,value])=>[key,sampleSchema(value,document,depth+1)]));if(schema.type==='integer'||schema.type==='number')return 0;if(schema.type==='boolean')return false;return schema.format==='date-time'?'2026-01-01T00:00:00Z':'string'}
