import {useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {Link} from 'react-router-dom'
import {AlertTriangle,CheckCircle2,ChevronDown,ChevronRight,Database,Info,RefreshCw,ServerCog,Stethoscope,XCircle} from 'lucide-react'
import {api} from '../api'
import type {ComponentInfo,DiagnosticCheck,DiagnosticResult} from '../types'
import ProgressBar from '../components/ProgressBar'
import {errorMessage} from '../errors'

const statusStyle={ok:'bg-emerald-50 text-emerald-700 ring-emerald-200',warning:'bg-amber-50 text-amber-700 ring-amber-200',error:'bg-rose-50 text-rose-700 ring-rose-200',info:'bg-blue-50 text-blue-700 ring-blue-200'}

export default function DiagnosticsPage(){
  const diagnostics=useQuery({queryKey:['diagnostics'],queryFn:()=>api.get<DiagnosticResult>('/api/diagnostics'),staleTime:0,retry:false})
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-blue-600">System health</p><h1 className="flex items-center gap-3 text-3xl font-bold"><Stethoscope size={30}/>Diagnostics</h1><p className="mt-1 text-slate-500">Shows every scanner component, including optional components that are not installed, plus storage, queues, roots, and registry access.</p></div><button className="btn-primary" disabled={diagnostics.isFetching} onClick={()=>diagnostics.refetch()}><RefreshCw className={diagnostics.isFetching?'animate-spin':''} size={16}/>Run diagnostics</button></div>
    {diagnostics.isError?<div className="card border-rose-200 p-5 text-rose-700">Diagnostics request failed: {errorMessage(diagnostics.error)}</div>:diagnostics.isLoading?<div className="card p-10"><ProgressBar indeterminate label="Running component checks" detail="Checking all scanner components, SQLite, storage, workers, scan roots, and registries"/></div>:<><Overall result={diagnostics.data!}/><ComponentInventory components={diagnostics.data!.components}/><section className="space-y-3"><div><h2 className="text-xl font-semibold">Operational checks</h2><p className="text-sm text-slate-500">Runtime, persistence, job workers, configured paths, and network endpoints.</p></div><div className="grid gap-4 lg:grid-cols-2">{diagnostics.data!.checks.map(item=><CheckCard key={item.id} item={item}/>)}</div></section><p className="text-xs text-slate-500">Last checked {new Date(diagnostics.data!.checked_at).toLocaleString()}. Registry checks make small requests to every configured vulnerability and Java database registry; they do not download database files.</p></>}
  </div>
}

function Overall({result}:{result:DiagnosticResult}){const ok=result.checks.filter(x=>x.status==='ok').length,info=result.checks.filter(x=>x.status==='info').length,warning=result.checks.filter(x=>x.status==='warning').length,error=result.checks.filter(x=>x.status==='error').length;return <div className={`card flex flex-wrap items-center justify-between gap-4 p-5 ring-1 ${statusStyle[result.overall]}`}><div className="flex items-center gap-3">{icon(result.overall,26)}<div><div className="text-lg font-bold capitalize">Overall status: {result.overall}</div><div className="text-sm opacity-80">Optional missing components are informational and do not reduce system health.</div></div></div><div className="flex flex-wrap gap-4 text-sm"><b>{ok} passed</b><b>{info} informational</b><b>{warning} warnings</b><b>{error} errors</b></div></div>}
function ComponentInventory({components}:{components:ComponentInfo[]}){return <section className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-semibold"><ServerCog size={21}/>Scanner components</h2><p className="text-sm text-slate-500">Complete inventory of bundled, installed, optional, and network-managed components.</p></div><Link className="btn-secondary" to="/components">Manage components</Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{components.map(component=><ComponentCard key={component.id} component={component}/>)}</div></section>}
function ComponentCard({component}:{component:ComponentInfo}){const missingRequired=component.required&&!component.installed,state=component.installed?'Installed':component.required?'Missing required component':'Not installed (optional)',tone=component.installed?statusStyle.ok:missingRequired?statusStyle.error:statusStyle.info;return <article className="card p-4"><div className="flex items-start gap-3"><span className={`rounded-lg p-2 ring-1 ${tone}`}><Database size={19}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{component.name}</h3><span className="rounded-full border px-2 py-0.5 text-[11px] font-semibold">{component.required?'Required':'Optional'}</span>{component.bundled&&<span className="rounded-full bg-violet-50 px-2 py-0.5 text-[11px] font-semibold text-violet-700">Bundled</span>}</div><p className="mt-1 text-xs text-slate-500">{component.description}</p></div></div><div className={`mt-3 rounded-lg px-3 py-2 text-sm font-medium ring-1 ${tone}`}>{state}</div><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><dt className="text-slate-500">Version / updated</dt><dd className="truncate text-right">{component.version||formatDate(component.updated_at)||'Not available'}</dd><dt className="text-slate-500">Size</dt><dd className="text-right">{component.size_bytes==null?'Not applicable':formatBytes(component.size_bytes)}</dd><dt className="text-slate-500">Update due</dt><dd className="truncate text-right">{formatDate(component.next_update)||'Not applicable'}</dd><dt className="text-slate-500">Latest job</dt><dd className="text-right capitalize">{component.latest_job?.status||'None'}</dd></dl>{component.repositories?.length?<details className="mt-3 text-xs"><summary className="cursor-pointer text-blue-600">Configured repositories ({component.repositories.length})</summary><div className="mt-2 space-y-1 break-all text-slate-500">{component.repositories.map(repository=><div key={repository}>{repository}</div>)}</div></details>:component.update_method&&<p className="mt-3 text-xs text-slate-500">{component.update_method}</p>}</article>}
function CheckCard({item}:{item:DiagnosticCheck}){const [open,setOpen]=useState(false),hasDetails=Object.keys(item.details).length>0;return <article className="card overflow-hidden"><button className="flex w-full items-center gap-3 p-4 text-left" onClick={()=>hasDetails&&setOpen(!open)}><span className={`rounded-lg p-2 ring-1 ${statusStyle[item.status]}`}>{icon(item.status,20)}</span><span className="min-w-0 flex-1"><span className="block font-semibold">{item.label}</span><span className="block text-sm text-slate-500">{item.summary}</span></span>{hasDetails&&(open?<ChevronDown size={18}/>:<ChevronRight size={18}/>)}</button>{open&&<pre className="max-h-64 overflow-auto border-t bg-slate-50 p-4 text-xs leading-5">{JSON.stringify(item.details,null,2)}</pre>}</article>}
function icon(status:DiagnosticCheck['status']|DiagnosticResult['overall'],size:number){return status==='ok'?<CheckCircle2 size={size}/>:status==='info'?<Info size={size}/>:status==='warning'?<AlertTriangle size={size}/>:<XCircle size={size}/>}
function formatDate(value?:string){return value?new Date(value).toLocaleString():''}
function formatBytes(value:number){if(value===0)return '0 B';const units=['B','KiB','MiB','GiB'];const index=Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return `${(value/1024**index).toFixed(index?1:0)} ${units[index]}`}
