import {FormEvent,useEffect,useMemo,useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {Boxes,CheckCircle2,ChevronLeft,ChevronRight,CircleDashed,FolderPlus,Images,Play,Save,Search,ShieldAlert,Trash2} from 'lucide-react'
import {Link} from 'react-router-dom'
import {api} from '../api'
import {useAuth} from '../auth'
import SeverityBadge from '../components/SeverityBadge'
import StatusBadge from '../components/StatusBadge'
import ArchiveSource from '../components/ArchiveSource'
import DestructiveConfirmDialog from '../components/DestructiveConfirmDialog'
import ReportExportControls from '../components/ReportExportControls'
import {errorMessage} from '../errors'
import {SEVERITIES,SEVERITY_COLORS} from '../severity'
import type {GroupColor,GroupOverview,GroupScanStatus,ImageArchive,ImageGroup,ImageGroupDetail} from '../types'

const colors:GroupColor[]=['blue','emerald','amber','rose','violet','slate']
const GROUP_PAGE_SIZE=50
const colorStyle:Record<GroupColor,string>={blue:'bg-blue-100 text-blue-800 ring-blue-300',emerald:'bg-emerald-100 text-emerald-800 ring-emerald-300',amber:'bg-amber-100 text-amber-800 ring-amber-300',rose:'bg-rose-100 text-rose-800 ring-rose-300',violet:'bg-violet-100 text-violet-800 ring-violet-300',slate:'bg-slate-100 text-slate-800 ring-slate-300'}
const statusStyle:Record<GroupScanStatus,string>={empty:'bg-slate-100 text-slate-700',unscanned:'bg-slate-100 text-slate-700',partial:'bg-amber-100 text-amber-800',scanned:'bg-emerald-100 text-emerald-800'}

export default function GroupsPage(){
  const auth=useAuth(),qc=useQueryClient(),canManage=auth.user?.role==='operator'||auth.user?.role==='admin'
  const [selected,setSelected]=useState<number|null>(null),[memberIds,setMemberIds]=useState<number[]>([]),[search,setSearch]=useState(''),[deleteOpen,setDeleteOpen]=useState(false)
  const [groupPage,setGroupPage]=useState(0)
  const groupOverview=useQuery({queryKey:['group-overview'],queryFn:()=>api.get<GroupOverview>('/api/groups/overview')})
  const groups=groupOverview.data?.groups||[]
  const images=useQuery({queryKey:['images'],queryFn:()=>api.get<ImageArchive[]>('/api/images')})
  const detail=useQuery({queryKey:['group',selected],queryFn:()=>api.get<ImageGroupDetail>(`/api/groups/${selected}`),enabled:selected!==null})
  useEffect(()=>{if(detail.data)setMemberIds(detail.data.members.map(image=>image.id))},[detail.data])
  const refresh=()=>{void qc.invalidateQueries({queryKey:['group-overview']});void qc.invalidateQueries({queryKey:['groups']});void qc.invalidateQueries({queryKey:['group']});void qc.invalidateQueries({queryKey:['images']});void qc.invalidateQueries({queryKey:['overview']})}
  const create=useMutation({mutationFn:(body:{name:string;description:string;color:GroupColor})=>api.post<ImageGroup>('/api/groups',body),onSuccess:value=>{refresh();setSelected(value.id)}})
  const update=useMutation({mutationFn:({id,body}:{id:number;body:{name:string;description:string;color:GroupColor}})=>api.post(`/api/groups/${id}/update`,body),onSuccess:refresh})
  const members=useMutation({mutationFn:({id,image_ids}:{id:number;image_ids:number[]})=>api.post(`/api/groups/${id}/members`,{image_ids}),onSuccess:refresh})
  const remove=useMutation({mutationFn:(id:number)=>api.delete(`/api/groups/${id}`),onSuccess:()=>{setDeleteOpen(false);setSelected(null);refresh()}})
  const scan=useMutation({mutationFn:(ids:number[])=>api.post('/api/scans',{image_ids:ids}),onSuccess:()=>{void qc.invalidateQueries({queryKey:['jobs']});void qc.invalidateQueries({queryKey:['images']})}})
  const error=groupOverview.error||images.error||detail.error||create.error||update.error||members.error||remove.error||scan.error
  const visible=useMemo(()=>(images.data||[]).filter(image=>(image.name+' '+image.source).toLowerCase().includes(search.toLowerCase())),[images.data,search])
  const groupPageCount=Math.max(1,Math.ceil(groups.length/GROUP_PAGE_SIZE)),visibleGroups=groups.slice(groupPage*GROUP_PAGE_SIZE,(groupPage+1)*GROUP_PAGE_SIZE)
  useEffect(()=>{if(groupPage>=groupPageCount)setGroupPage(groupPageCount-1)},[groupPage,groupPageCount])
  const selectGroup=(id:number)=>{setSelected(id);const index=groups.findIndex(group=>group.id===id);if(index>=0)setGroupPage(Math.floor(index/GROUP_PAGE_SIZE))}
  const busy=create.isPending||update.isPending||members.isPending||remove.isPending||scan.isPending
  return <div className="space-y-6">
    <div><p className="text-sm font-medium text-blue-600">Image organization</p><h1 className="flex items-center gap-3 text-3xl font-bold"><Boxes size={30}/>Image groups</h1><p className="mt-1 text-slate-500">Organize related archives, review their combined risk, and scan every image in a group together.</p></div>
    {error&&<p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{errorMessage(error,'Unable to update image groups')}</p>}
    <GroupAnalytics overview={groupOverview.data} loading={groupOverview.isLoading} onSelect={selectGroup}/>
    {canManage&&<CreateGroup busy={busy} onCreate={body=>create.mutate(body)}/>}
    <div className="grid gap-5 lg:grid-cols-[380px_1fr]">
      <section className="card overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Groups</h2><p className="text-sm text-slate-500">{groups.length} group(s)</p></div><div className="max-h-[720px] overflow-auto">{visibleGroups.map(group=><button key={group.id} className={`w-full border-b p-4 text-left transition hover:bg-slate-50 ${selected===group.id?'bg-blue-50':''}`} onClick={()=>selectGroup(group.id)}><div className="flex items-center justify-between gap-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ${colorStyle[group.color]}`}>{group.name}</span><span className="text-xs text-slate-500">{group.member_count} images</span></div><p className="mt-2 line-clamp-2 text-sm text-slate-500">{group.description||'No description'}</p><div className="mt-3 flex flex-wrap items-center gap-1"><GroupStatusBadge status={group.scan_status}/>{Object.entries(group.severity).map(([severity,count])=><SeverityBadge key={severity} value={severity} count={count}/>)}</div></button>)}</div>{!groups.length&&<p className="p-10 text-center text-sm text-slate-500">Create a group to organize related images.</p>}{groupPageCount>1&&<div className="flex items-center justify-between gap-3 border-t px-3 py-2"><button type="button" className="btn-secondary px-2" disabled={groupPage===0} onClick={()=>setGroupPage(page=>Math.max(0,page-1))} aria-label="Previous group page"><ChevronLeft size={16}/></button><span className="text-xs text-slate-500">Page {groupPage+1} of {groupPageCount}</span><button type="button" className="btn-secondary px-2" disabled={groupPage+1>=groupPageCount} onClick={()=>setGroupPage(page=>Math.min(groupPageCount-1,page+1))} aria-label="Next group page"><ChevronRight size={16}/></button></div>}</section>
      {!selected?<section className="card flex min-h-96 items-center justify-center p-10 text-center text-slate-500"><div><Boxes className="mx-auto mb-3" size={36}/><p>Select a group to manage its images and view combined risk.</p></div></section>:detail.isLoading?<section className="card p-10 text-center text-slate-500">Loading group...</section>:detail.data&&<section className="space-y-5"><GroupEditor key={detail.data.id+detail.data.updated_at} group={detail.data} canManage={canManage} busy={busy} onUpdate={body=>update.mutate({id:detail.data!.id,body})} onDelete={()=>setDeleteOpen(true)} onScan={()=>scan.mutate(detail.data!.members.map(image=>image.id))}/><GroupExports group={detail.data}/><div className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="font-semibold">Group membership</h2><p className="text-sm text-slate-500">An image can belong to more than one group.</p></div>{canManage&&<button className="btn-primary" disabled={busy} onClick={()=>members.mutate({id:detail.data!.id,image_ids:memberIds})}><Save size={16}/>Save membership</button>}</div><div className="border-b p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input className="input pl-9" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search images"/></div></div><div className="max-h-[480px] overflow-auto">{visible.map(image=><label key={image.id} className="flex cursor-pointer items-center gap-3 border-b p-4 hover:bg-slate-50"><input type="checkbox" disabled={!canManage||busy} checked={memberIds.includes(image.id)} onChange={()=>setMemberIds(value=>value.includes(image.id)?value.filter(id=>id!==image.id):[...value,image.id])}/><div className="min-w-0 flex-1"><Link to={`/images/${image.id}`} className="font-semibold text-blue-700 hover:underline" onClick={event=>event.stopPropagation()}>{image.name}</Link><div className="mt-1"><ArchiveSource source={image.source} compact/></div></div><StatusBadge status={image.latest_scan?.status}/></label>)}</div></div></section>}
    </div>
    {deleteOpen&&detail.data&&<DestructiveConfirmDialog title={`Delete ${detail.data.name}?`} description="This removes the organizational group and its memberships. Image archives and all saved scan evidence remain unchanged." confirmation={detail.data.name} items={detail.data.members.map(image=>image.name)} summaries={[{label:'Group',value:detail.data.name},{label:'Memberships',value:String(detail.data.member_count)}]} warning="Images, TAR archives, findings, package data, raw JSON, and scan history are not deleted." busy={busy} error={errorMessage(remove.error,'')} confirmLabel="Delete group" onCancel={()=>setDeleteOpen(false)} onConfirm={()=>remove.mutate(detail.data!.id)}/>}
  </div>
}

function GroupAnalytics({overview,loading,onSelect}:{overview?:GroupOverview;loading:boolean;onSelect:(id:number)=>void}){
  if(loading)return <section className="card p-8 text-center text-sm text-slate-500">Loading group analytics...</section>
  const coverage=overview?.membership_count?overview.scanned_membership_count/overview.membership_count*100:0
  const maxSeverity=Math.max(1,...SEVERITIES.map(level=>overview?.severity[level]||0))
  const ranked=[...(overview?.groups||[])].sort((left,right)=>right.total_findings-left.total_findings||left.name.localeCompare(right.name)).slice(0,5)
  return <section className="space-y-4" aria-labelledby="group-overview-heading">
    <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-600">Latest completed scans</p><h2 id="group-overview-heading" className="mt-1 text-xl font-bold">Group overview</h2><p className="mt-1 text-sm text-slate-500">Memberships are counted once per group. An image in several groups contributes once to each group.</p></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Metric icon={<Boxes/>} label="Groups" value={overview?.group_count||0} detail={`${overview?.statuses.empty||0} empty`}/>
      <Metric icon={<Images/>} label="Memberships" value={overview?.membership_count||0} detail="Visible image memberships"/>
      <Metric icon={<CheckCircle2/>} label="Scanned memberships" value={overview?.scanned_membership_count||0} detail={`${coverage.toFixed(1)}% coverage`}/>
      <Metric icon={<CircleDashed/>} label="Awaiting completed scan" value={overview?.unscanned_membership_count||0} detail="No completed scan available"/>
    </div>
    <div className="grid gap-4 xl:grid-cols-2">
      <article className="card p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Risk composition</p><h3 className="mt-1 font-semibold">Findings by severity</h3></div><div className="text-right"><p className="text-2xl font-bold">{(overview?.total_findings||0).toLocaleString()}</p><p className="text-xs text-slate-500">membership-weighted findings</p></div></div><div className="mt-5 space-y-3">{SEVERITIES.map(level=>{const value=overview?.severity[level]||0;return <div key={level}><div className="mb-1.5 flex items-center justify-between text-xs"><span className="font-semibold">{level}</span><span className="text-slate-500">{value.toLocaleString()}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{width:`${value/maxSeverity*100}%`,backgroundColor:SEVERITY_COLORS[level]}}/></div></div>})}</div></article>
      <article className="card overflow-hidden"><div className="border-b p-5"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Prioritize review</p><h3 className="mt-1 font-semibold">Highest-risk groups</h3></div>{ranked.length?<ol className="divide-y">{ranked.map((group,index)=><li key={group.id}><button type="button" className="flex min-h-16 w-full items-center gap-3 px-4 py-3 text-left transition hover:bg-slate-50" onClick={()=>onSelect(group.id)}><span className="flex size-7 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold text-slate-500">{index+1}</span><span className="min-w-0 flex-1"><span className="block truncate font-semibold">{group.name}</span><span className="mt-1 flex flex-wrap items-center gap-2 text-xs text-slate-500"><GroupStatusBadge status={group.scan_status}/><span>{group.scanned_count}/{group.member_count} scanned</span></span></span><span className="text-right"><span className="block font-bold">{group.total_findings.toLocaleString()}</span><span className="text-xs text-slate-500">findings</span></span></button></li>)}</ol>:<div className="p-10 text-center text-sm text-slate-500"><ShieldAlert className="mx-auto mb-3" size={28}/>Groups with completed scans will appear here.</div>}</article>
    </div>
  </section>
}

function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:number;detail:string}){return <article className="card p-4"><div className="flex items-start gap-3"><span className="rounded-xl bg-blue-50 p-2.5 text-blue-600">{icon}</span><div className="min-w-0"><p className="text-2xl font-bold">{value.toLocaleString()}</p><h3 className="text-sm font-semibold">{label}</h3><p className="mt-1 truncate text-xs text-slate-500">{detail}</p></div></div></article>}

function GroupStatusBadge({status}:{status:GroupScanStatus}){return <span className={`inline-flex rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${statusStyle[status]}`}>{status}</span>}

function CreateGroup({busy,onCreate}:{busy:boolean;onCreate:(body:{name:string;description:string;color:GroupColor})=>void}){function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);onCreate({name:String(data.get('name')),description:String(data.get('description')),color:String(data.get('color')) as GroupColor})}return <section className="card p-5"><h2 className="mb-3 flex items-center gap-2 font-semibold"><FolderPlus size={18}/>Create group</h2><form className="grid gap-3 lg:grid-cols-[220px_1fr_160px_auto]" onSubmit={submit}><input className="input" name="name" required maxLength={100} placeholder="Group name"/><input className="input" name="description" maxLength={500} placeholder="Description, service, environment, or owner"/><select className="input" name="color" defaultValue="blue">{colors.map(color=><option key={color}>{color}</option>)}</select><button className="btn-primary" disabled={busy}><FolderPlus size={16}/>Create</button></form></section>}

function GroupExports({group}:{group:ImageGroupDetail}){return <section className="card p-5"><div><h2 className="font-semibold">Export group snapshot</h2><p className="mb-4 mt-1 max-w-2xl text-sm text-slate-500">Exports the latest completed scan for {group.scanned_count} of {group.member_count} visible members. {group.unscanned_count?`${group.unscanned_count} member(s) without a completed scan are listed as excluded.`:'Every visible member is covered.'}</p><ReportExportControls disabled={!group.scanned_count} urlFor={format=>`/api/exports?group_ids=${group.id}&format=${format}`}/></div>{!group.scanned_count&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Complete at least one member scan before exporting this group.</p>}</section>}

function GroupEditor({group,canManage,busy,onUpdate,onDelete,onScan}:{group:ImageGroupDetail;canManage:boolean;busy:boolean;onUpdate:(body:{name:string;description:string;color:GroupColor})=>void;onDelete:()=>void;onScan:()=>void}){const [name,setName]=useState(group.name),[description,setDescription]=useState(group.description),[color,setColor]=useState(group.color);return <section className="card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className={`rounded-full px-3 py-1 text-sm font-semibold ring-1 ${colorStyle[group.color]}`}>{group.name}</span><p className="mt-3 max-w-3xl text-sm text-slate-500">{group.description||'No description'}</p><div className="mt-3 flex flex-wrap gap-2"><span className="text-sm font-semibold">{group.member_count} images</span><span className="text-sm text-slate-500">{group.total_findings.toLocaleString()} findings</span>{Object.entries(group.severity).map(([severity,count])=><SeverityBadge key={severity} value={severity} count={count}/>)}</div></div>{canManage&&<div className="flex gap-2"><button className="btn-primary" disabled={busy||!group.members.length} onClick={onScan}><Play size={16}/>Scan group</button><button className="btn-secondary text-rose-700" disabled={busy} onClick={onDelete}><Trash2 size={15}/>Delete group</button></div>}</div>{canManage&&<form className="mt-5 grid gap-3 border-t pt-5 lg:grid-cols-[220px_1fr_160px_auto]" onSubmit={event=>{event.preventDefault();onUpdate({name,description,color})}}><input className="input" value={name} onChange={event=>setName(event.target.value)} required maxLength={100}/><input className="input" value={description} onChange={event=>setDescription(event.target.value)} maxLength={500} placeholder="Description"/><select className="input" value={color} onChange={event=>setColor(event.target.value as GroupColor)}>{colors.map(item=><option key={item}>{item}</option>)}</select><button className="btn-secondary" disabled={busy}><Save size={16}/>Save details</button></form>}</section>}
