import {lazy,Suspense,useEffect,useMemo,useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {Link} from 'react-router-dom'
import {Archive,CheckSquare,ChevronLeft,ChevronRight,Download,FolderPlus,Play,RefreshCw,Search,ShieldAlert,Trash2} from 'lucide-react'
import {api} from '../api'
import {useAuth} from '../auth'
import type {ImageArchive,ImageGroup,Overview} from '../types'
import SeverityBadge from '../components/SeverityBadge'
import ProgressBar from '../components/ProgressBar'
import DestructiveConfirmDialog from '../components/DestructiveConfirmDialog'
import StatusBadge from '../components/StatusBadge'
import ArchiveSource from '../components/ArchiveSource'
import {errorMessage} from '../errors'

const DashboardCharts=lazy(()=>import('../components/DashboardCharts'))
const PAGE_SIZE=100

export default function OverviewPage(){
  const auth=useAuth(),qc=useQueryClient(),canManage=auth.user?.role==='operator'||auth.user?.role==='admin',admin=auth.user?.role==='admin'
  const [selected,setSelected]=useState<number[]>([]),[search,setSearch]=useState(''),[groupId,setGroupId]=useState(''),[deleteOpen,setDeleteOpen]=useState(false),[page,setPage]=useState(0)
  const overview=useQuery({queryKey:['overview'],queryFn:()=>api.get<Overview>('/api/overview')})
  const images=useQuery({queryKey:['images'],queryFn:()=>api.get<ImageArchive[]>('/api/images')})
  const groups=useQuery({queryKey:['groups'],queryFn:()=>api.get<ImageGroup[]>('/api/groups')})
  const refresh=()=>{void qc.invalidateQueries({queryKey:['images']});void qc.invalidateQueries({queryKey:['overview']});void qc.invalidateQueries({queryKey:['groups']});void qc.invalidateQueries({queryKey:['jobs']})}
  const completed=()=>{setSelected([]);setDeleteOpen(false);refresh()}
  const scan=useMutation({mutationFn:(ids:number[])=>api.post('/api/scans',{image_ids:ids}),onSuccess:completed})
  const discover=useMutation({mutationFn:()=>api.post('/api/discover'),onSuccess:refresh})
  const addToGroup=useMutation({mutationFn:({group,image_ids}:{group:number;image_ids:number[]})=>api.post(`/api/groups/${group}/members/add`,{image_ids}),onSuccess:completed})
  const removeImages=useMutation({mutationFn:(image_ids:number[])=>api.post('/api/images/bulk-delete',{image_ids}),onSuccess:completed})
  const shown=useMemo(()=>{const needle=search.trim().toLocaleLowerCase();return (images.data||[]).filter(image=>!needle||(image.name+' '+image.source).toLocaleLowerCase().includes(needle))},[images.data,search])
  const pageCount=Math.max(1,Math.ceil(shown.length/PAGE_SIZE)),visible=shown.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE)
  const selectedSet=useMemo(()=>new Set(selected),[selected])
  const selectedImages=(images.data||[]).filter(image=>selectedSet.has(image.id)),activeSelected=selectedImages.some(image=>image.latest_scan&&['queued','running'].includes(image.latest_scan.status)),reportSelected=selectedImages.some(image=>image.source==='report')
  useEffect(()=>setPage(0),[search])
  useEffect(()=>setPage(value=>Math.min(value,pageCount-1)),[pageCount])
  const busy=scan.isPending||discover.isPending||addToGroup.isPending||removeImages.isPending
  const error=scan.error||discover.error||addToGroup.error||removeImages.error||overview.error||images.error||groups.error
  const toggle=(id:number)=>setSelected(value=>value.includes(id)?value.filter(item=>item!==id):[...value,id])
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-blue-600">Local image security</p><h1 className="text-3xl font-bold tracking-tight">Vulnerability overview</h1><p className="mt-1 text-slate-500">Discover archives, organize images, queue scans, and review saved results.</p></div><button className="btn-secondary" disabled={discover.isPending} onClick={()=>discover.mutate()}><RefreshCw className={discover.isPending?'animate-spin':''} size={16}/>{discover.isPending?'Discovering':'Discover'}</button></div>
    {error&&!deleteOpen&&<p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{errorMessage(error,'Unable to load or update the overview')}</p>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={<Archive/>} label="Images / reports" value={overview.data?.image_count||0}/><Stat icon={<CheckSquare/>} label="Analyzed" value={overview.data?.scanned_count||0}/><Stat icon={<ShieldAlert/>} label="Findings" value={overview.data?.total_findings||0}/><Stat icon={<Play/>} label="Active / queued" value={(overview.data?.statuses.running||0)+(overview.data?.statuses.queued||0)}/></div>
    <Suspense fallback={<div className="grid gap-5 lg:grid-cols-3"><div className="card h-80 animate-pulse bg-slate-100 lg:col-span-3"/></div>}><DashboardCharts overview={overview.data}/></Suspense>
    <section className="card overflow-hidden">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-semibold">Images and imported reports</h2><p className="text-sm text-slate-500">Select entries to scan when an archive is available, organize, or remove together.</p></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input className="input pl-9" placeholder="Search images and reports" value={search} onChange={event=>setSearch(event.target.value)}/></div><button className="btn-secondary" onClick={()=>setSelected(selected.length===shown.length?[]:shown.map(image=>image.id))}>{selected.length===shown.length&&shown.length?'Clear':'Select all'}</button></div></div>
      {selectedImages.length>0&&<div className="flex flex-wrap items-center gap-2 border-b bg-blue-50 p-3"><span className="mr-1 text-sm font-semibold text-blue-700">{selectedImages.length} selected</span>{canManage&&<button className="btn-primary" disabled={busy||reportSelected} title={reportSelected?'Imported reports do not include an image archive to scan':'Scan selected images'} onClick={()=>scan.mutate(selected)}><Play size={15}/>Scan</button>}{canManage&&<><select className="input max-w-56" value={groupId} onChange={event=>setGroupId(event.target.value)}><option value="">Choose a group...</option>{(groups.data||[]).map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><button className="btn-secondary" disabled={busy||!groupId} onClick={()=>addToGroup.mutate({group:Number(groupId),image_ids:selected})}><FolderPlus size={15}/>Add to group</button></>}{admin&&<button className="btn-secondary text-rose-700" disabled={busy||activeSelected} title={activeSelected?'Cancel active scans before removing these images':'Remove selected images or reports'} onClick={()=>setDeleteOpen(true)}><Trash2 size={15}/>Delete</button>}<button className="btn-secondary ml-auto" disabled={busy} onClick={()=>setSelected([])}>Clear selection</button></div>}
      <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="w-12 p-4"></th><th className="p-4">Image or report</th><th className="p-4">Status and progress</th><th className="p-4">Findings</th><th className="p-4">Severities</th><th className="p-4">Size</th><th className="p-4 text-right">Download</th></tr></thead><tbody>{visible.map(image=><ImageRow key={image.id} image={image} checked={selectedSet.has(image.id)} canDownload={canManage} onToggle={()=>toggle(image.id)}/>)}</tbody></table></div>
      {shown.length>PAGE_SIZE&&<div className="flex items-center justify-between gap-3 border-t px-4 py-3 text-sm"><span className="text-slate-500">Showing {(page*PAGE_SIZE+1).toLocaleString()}–{Math.min((page+1)*PAGE_SIZE,shown.length).toLocaleString()} of {shown.length.toLocaleString()}</span><div className="flex items-center gap-2"><button className="btn-secondary p-2" aria-label="Previous image page" disabled={page===0} onClick={()=>setPage(value=>value-1)}><ChevronLeft size={16}/></button><span className="min-w-20 text-center font-medium">{page+1} / {pageCount}</span><button className="btn-secondary p-2" aria-label="Next image page" disabled={page>=pageCount-1} onClick={()=>setPage(value=>value+1)}><ChevronRight size={16}/></button></div></div>}
    </section>
    {deleteOpen&&<DestructiveConfirmDialog title={`Delete ${selectedImages.length} selected entr${selectedImages.length===1?'y':'ies'}?`} description="Uploaded archives and imported report-only entries will be permanently deleted. Read-only mounted archives will be hidden and remain restorable from Data Management." confirmation={selectedImages.length===1?selectedImages[0].name:`DELETE ${selectedImages.length} IMAGES`} items={selectedImages.map(image=>image.source==='report'?`${image.name} · report only`:`${image.name} · ${formatBytes(image.size)}`)} summaries={[{label:'Selected entries',value:String(selectedImages.length)},{label:'Saved history',value:'All normalized scan evidence'}]} warning="The server validates the entire selection before removal. Any active scan blocks the operation. Keep exported JSON if you may need to import report-only history again." busy={busy} error={errorMessage(removeImages.error,'')} confirmLabel="Delete selected entries" onCancel={()=>setDeleteOpen(false)} onConfirm={()=>removeImages.mutate(selected)}/>}
  </div>
}

function ImageRow({image,checked,canDownload,onToggle}:{image:ImageArchive;checked:boolean;canDownload:boolean;onToggle:()=>void}){const active=image.latest_scan&&(image.latest_scan.status==='queued'||image.latest_scan.status==='running'),reportOnly=image.source==='report';return <tr className={`border-t hover:bg-slate-50 ${checked?'bg-blue-50/70':''}`}><td className="p-4"><input className="h-4 w-4 accent-blue-600" type="checkbox" aria-label={`Select ${image.name}`} checked={checked} onChange={onToggle}/></td><td className="p-4"><Link to={`/images/${image.id}`} className="font-medium text-blue-700 hover:underline">{image.name}</Link><div className="mt-1"><ArchiveSource source={image.source} compact/></div>{image.groups.length>0&&<div className="mt-2 flex flex-wrap gap-1">{image.groups.map(group=><span key={group.id} className="rounded-full bg-slate-100 px-2 py-0.5 text-[11px] font-semibold text-slate-700">{group.name}</span>)}</div>}</td><td className="min-w-56 p-4">{active?<ProgressBar compact value={image.latest_scan!.progress} label={image.latest_scan!.stage.replace(/_/g,' ')} detail={image.latest_scan!.message}/>:<StatusBadge status={image.latest_scan?.status}/>}</td><td className="p-4 font-semibold tabular-nums">{image.latest_scan?.total??0}</td><td className="p-4"><div className="flex flex-wrap gap-1">{Object.entries(image.latest_scan?.counts||{}).map(([severity,count])=><SeverityBadge key={severity} value={severity} count={count}/>)}</div></td><td className="p-4">{reportOnly?'No TAR':formatBytes(image.size)}</td><td className="p-4 text-right">{reportOnly?<span className="text-xs text-slate-400">Not included</span>:canDownload?<a className="btn-secondary" href={`/api/images/${image.id}/archive`} download><Download size={15}/>TAR</a>:<span className="text-xs text-slate-400">Restricted</span>}</td></tr>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="card flex items-center gap-4 p-5"><span className="rounded-lg bg-blue-50 p-3 text-blue-600">{icon}</span><div><div className="text-2xl font-bold">{value.toLocaleString()}</div><div className="text-sm text-slate-500">{label}</div></div></div>}
function formatBytes(value:number){return `${(value/1024/1024).toFixed(1)} MB`}
